/* ISR definitions */

isr0:
	pushw $0
	pushw $0
	jmp isr_common
isr1:
	pushw $0
	pushw $1
	jmp isr_common
isr2:
	pushw $0
	pushw $2
	jmp isr_common
isr3:
	pushw $0
	pushw $3
	jmp isr_common
isr4:
	pushw $0
	pushw $4
	jmp isr_common
isr5:
	pushw $0
	pushw $5
	jmp isr_common
isr6:
	pushw $0
	pushw $6
	jmp isr_common
isr7:
	pushw $0
	pushw $7
	jmp isr_common
isr8:
	pushw $8
	jmp isr_common
isr9:
	pushw $0
	pushw $9
	jmp isr_common
isr10:
	pushw $10
	jmp isr_common
isr11:
	pushw $11
	jmp isr_common
isr12:
	pushw $12
	jmp isr_common
isr13:
	pushw $13
	jmp isr_common
isr14:
	pushw $14
	jmp isr_common
isr15:
	pushw $0
	pushw $15
	jmp isr_common
isr16:
	pushw $0
	pushw $16
	jmp isr_common
isr17:
	pushw $0
	pushw $17
	jmp isr_common
isr18:
	pushw $0
	pushw $18
	jmp isr_common
isr19:
	pushw $0
	pushw $19
	jmp isr_common
isr20:
	pushw $0
	pushw $20
	jmp isr_common
isr21:
	pushw $0
	pushw $21
	jmp isr_common
isr22:
	pushw $0
	pushw $22
	jmp isr_common
isr23:
	pushw $0
	pushw $23
	jmp isr_common
isr24:
	pushw $0
	pushw $24
	jmp isr_common
isr25:
	pushw $0
	pushw $25
	jmp isr_common
isr26:
	pushw $0
	pushw $26
	jmp isr_common
isr27:
	pushw $0
	pushw $27
	jmp isr_common
isr28:
	pushw $0
	pushw $28
	jmp isr_common
isr29:
	pushw $0
	pushw $29
	jmp isr_common
isr30:
	pushw $0
	pushw $30
	jmp isr_common
isr31:
	pushw $0
	pushw $31
	jmp isr_common
isr32:
	pushw $0
	pushw $32
	jmp isr_common
isr33:
	pushw $0
	pushw $33
	jmp isr_common
isr34:
	pushw $0
	pushw $34
	jmp isr_common
isr35:
	pushw $0
	pushw $35
	jmp isr_common
isr36:
	pushw $0
	pushw $36
	jmp isr_common
isr37:
	pushw $0
	pushw $37
	jmp isr_common
isr38:
	pushw $0
	pushw $38
	jmp isr_common
isr39:
	pushw $0
	pushw $39
	jmp isr_common
isr40:
	pushw $0
	pushw $40
	jmp isr_common
isr41:
	pushw $0
	pushw $41
	jmp isr_common
isr42:
	pushw $0
	pushw $42
	jmp isr_common
isr43:
	pushw $0
	pushw $43
	jmp isr_common
isr44:
	pushw $0
	pushw $44
	jmp isr_common
isr45:
	pushw $0
	pushw $45
	jmp isr_common
isr46:
	pushw $0
	pushw $46
	jmp isr_common
isr47:
	pushw $0
	pushw $47
	jmp isr_common
isr48:
	pushw $0
	pushw $48
	jmp isr_common
isr49:
	pushw $0
	pushw $49
	jmp isr_common
isr50:
	pushw $0
	pushw $50
	jmp isr_common
isr51:
	pushw $0
	pushw $51
	jmp isr_common
isr52:
	pushw $0
	pushw $52
	jmp isr_common
isr53:
	pushw $0
	pushw $53
	jmp isr_common
isr54:
	pushw $0
	pushw $54
	jmp isr_common
isr55:
	pushw $0
	pushw $55
	jmp isr_common
isr56:
	pushw $0
	pushw $56
	jmp isr_common
isr57:
	pushw $0
	pushw $57
	jmp isr_common
isr58:
	pushw $0
	pushw $58
	jmp isr_common
isr59:
	pushw $0
	pushw $59
	jmp isr_common
isr60:
	pushw $0
	pushw $60
	jmp isr_common
isr61:
	pushw $0
	pushw $61
	jmp isr_common
isr62:
	pushw $0
	pushw $62
	jmp isr_common
isr63:
	pushw $0
	pushw $63
	jmp isr_common
isr64:
	pushw $0
	pushw $64
	jmp isr_common
isr65:
	pushw $0
	pushw $65
	jmp isr_common
isr66:
	pushw $0
	pushw $66
	jmp isr_common
isr67:
	pushw $0
	pushw $67
	jmp isr_common
isr68:
	pushw $0
	pushw $68
	jmp isr_common
isr69:
	pushw $0
	pushw $69
	jmp isr_common
isr70:
	pushw $0
	pushw $70
	jmp isr_common
isr71:
	pushw $0
	pushw $71
	jmp isr_common
isr72:
	pushw $0
	pushw $72
	jmp isr_common
isr73:
	pushw $0
	pushw $73
	jmp isr_common
isr74:
	pushw $0
	pushw $74
	jmp isr_common
isr75:
	pushw $0
	pushw $75
	jmp isr_common
isr76:
	pushw $0
	pushw $76
	jmp isr_common
isr77:
	pushw $0
	pushw $77
	jmp isr_common
isr78:
	pushw $0
	pushw $78
	jmp isr_common
isr79:
	pushw $0
	pushw $79
	jmp isr_common
isr80:
	pushw $0
	pushw $80
	jmp isr_common
isr81:
	pushw $0
	pushw $81
	jmp isr_common
isr82:
	pushw $0
	pushw $82
	jmp isr_common
isr83:
	pushw $0
	pushw $83
	jmp isr_common
isr84:
	pushw $0
	pushw $84
	jmp isr_common
isr85:
	pushw $0
	pushw $85
	jmp isr_common
isr86:
	pushw $0
	pushw $86
	jmp isr_common
isr87:
	pushw $0
	pushw $87
	jmp isr_common
isr88:
	pushw $0
	pushw $88
	jmp isr_common
isr89:
	pushw $0
	pushw $89
	jmp isr_common
isr90:
	pushw $0
	pushw $90
	jmp isr_common
isr91:
	pushw $0
	pushw $91
	jmp isr_common
isr92:
	pushw $0
	pushw $92
	jmp isr_common
isr93:
	pushw $0
	pushw $93
	jmp isr_common
isr94:
	pushw $0
	pushw $94
	jmp isr_common
isr95:
	pushw $0
	pushw $95
	jmp isr_common
isr96:
	pushw $0
	pushw $96
	jmp isr_common
isr97:
	pushw $0
	pushw $97
	jmp isr_common
isr98:
	pushw $0
	pushw $98
	jmp isr_common
isr99:
	pushw $0
	pushw $99
	jmp isr_common
isr100:
	pushw $0
	pushw $100
	jmp isr_common
isr101:
	pushw $0
	pushw $101
	jmp isr_common
isr102:
	pushw $0
	pushw $102
	jmp isr_common
isr103:
	pushw $0
	pushw $103
	jmp isr_common
isr104:
	pushw $0
	pushw $104
	jmp isr_common
isr105:
	pushw $0
	pushw $105
	jmp isr_common
isr106:
	pushw $0
	pushw $106
	jmp isr_common
isr107:
	pushw $0
	pushw $107
	jmp isr_common
isr108:
	pushw $0
	pushw $108
	jmp isr_common
isr109:
	pushw $0
	pushw $109
	jmp isr_common
isr110:
	pushw $0
	pushw $110
	jmp isr_common
isr111:
	pushw $0
	pushw $111
	jmp isr_common
isr112:
	pushw $0
	pushw $112
	jmp isr_common
isr113:
	pushw $0
	pushw $113
	jmp isr_common
isr114:
	pushw $0
	pushw $114
	jmp isr_common
isr115:
	pushw $0
	pushw $115
	jmp isr_common
isr116:
	pushw $0
	pushw $116
	jmp isr_common
isr117:
	pushw $0
	pushw $117
	jmp isr_common
isr118:
	pushw $0
	pushw $118
	jmp isr_common
isr119:
	pushw $0
	pushw $119
	jmp isr_common
isr120:
	pushw $0
	pushw $120
	jmp isr_common
isr121:
	pushw $0
	pushw $121
	jmp isr_common
isr122:
	pushw $0
	pushw $122
	jmp isr_common
isr123:
	pushw $0
	pushw $123
	jmp isr_common
isr124:
	pushw $0
	pushw $124
	jmp isr_common
isr125:
	pushw $0
	pushw $125
	jmp isr_common
isr126:
	pushw $0
	pushw $126
	jmp isr_common
isr127:
	pushw $0
	pushw $127
	jmp isr_common
isr128:
	pushw $0
	pushw $128
	jmp isr_common
isr129:
	pushw $0
	pushw $129
	jmp isr_common
isr130:
	pushw $0
	pushw $130
	jmp isr_common
isr131:
	pushw $0
	pushw $131
	jmp isr_common
isr132:
	pushw $0
	pushw $132
	jmp isr_common
isr133:
	pushw $0
	pushw $133
	jmp isr_common
isr134:
	pushw $0
	pushw $134
	jmp isr_common
isr135:
	pushw $0
	pushw $135
	jmp isr_common
isr136:
	pushw $0
	pushw $136
	jmp isr_common
isr137:
	pushw $0
	pushw $137
	jmp isr_common
isr138:
	pushw $0
	pushw $138
	jmp isr_common
isr139:
	pushw $0
	pushw $139
	jmp isr_common
isr140:
	pushw $0
	pushw $140
	jmp isr_common
isr141:
	pushw $0
	pushw $141
	jmp isr_common
isr142:
	pushw $0
	pushw $142
	jmp isr_common
isr143:
	pushw $0
	pushw $143
	jmp isr_common
isr144:
	pushw $0
	pushw $144
	jmp isr_common
isr145:
	pushw $0
	pushw $145
	jmp isr_common
isr146:
	pushw $0
	pushw $146
	jmp isr_common
isr147:
	pushw $0
	pushw $147
	jmp isr_common
isr148:
	pushw $0
	pushw $148
	jmp isr_common
isr149:
	pushw $0
	pushw $149
	jmp isr_common
isr150:
	pushw $0
	pushw $150
	jmp isr_common
isr151:
	pushw $0
	pushw $151
	jmp isr_common
isr152:
	pushw $0
	pushw $152
	jmp isr_common
isr153:
	pushw $0
	pushw $153
	jmp isr_common
isr154:
	pushw $0
	pushw $154
	jmp isr_common
isr155:
	pushw $0
	pushw $155
	jmp isr_common
isr156:
	pushw $0
	pushw $156
	jmp isr_common
isr157:
	pushw $0
	pushw $157
	jmp isr_common
isr158:
	pushw $0
	pushw $158
	jmp isr_common
isr159:
	pushw $0
	pushw $159
	jmp isr_common
isr160:
	pushw $0
	pushw $160
	jmp isr_common
isr161:
	pushw $0
	pushw $161
	jmp isr_common
isr162:
	pushw $0
	pushw $162
	jmp isr_common
isr163:
	pushw $0
	pushw $163
	jmp isr_common
isr164:
	pushw $0
	pushw $164
	jmp isr_common
isr165:
	pushw $0
	pushw $165
	jmp isr_common
isr166:
	pushw $0
	pushw $166
	jmp isr_common
isr167:
	pushw $0
	pushw $167
	jmp isr_common
isr168:
	pushw $0
	pushw $168
	jmp isr_common
isr169:
	pushw $0
	pushw $169
	jmp isr_common
isr170:
	pushw $0
	pushw $170
	jmp isr_common
isr171:
	pushw $0
	pushw $171
	jmp isr_common
isr172:
	pushw $0
	pushw $172
	jmp isr_common
isr173:
	pushw $0
	pushw $173
	jmp isr_common
isr174:
	pushw $0
	pushw $174
	jmp isr_common
isr175:
	pushw $0
	pushw $175
	jmp isr_common
isr176:
	pushw $0
	pushw $176
	jmp isr_common
isr177:
	pushw $0
	pushw $177
	jmp isr_common
isr178:
	pushw $0
	pushw $178
	jmp isr_common
isr179:
	pushw $0
	pushw $179
	jmp isr_common
isr180:
	pushw $0
	pushw $180
	jmp isr_common
isr181:
	pushw $0
	pushw $181
	jmp isr_common
isr182:
	pushw $0
	pushw $182
	jmp isr_common
isr183:
	pushw $0
	pushw $183
	jmp isr_common
isr184:
	pushw $0
	pushw $184
	jmp isr_common
isr185:
	pushw $0
	pushw $185
	jmp isr_common
isr186:
	pushw $0
	pushw $186
	jmp isr_common
isr187:
	pushw $0
	pushw $187
	jmp isr_common
isr188:
	pushw $0
	pushw $188
	jmp isr_common
isr189:
	pushw $0
	pushw $189
	jmp isr_common
isr190:
	pushw $0
	pushw $190
	jmp isr_common
isr191:
	pushw $0
	pushw $191
	jmp isr_common
isr192:
	pushw $0
	pushw $192
	jmp isr_common
isr193:
	pushw $0
	pushw $193
	jmp isr_common
isr194:
	pushw $0
	pushw $194
	jmp isr_common
isr195:
	pushw $0
	pushw $195
	jmp isr_common
isr196:
	pushw $0
	pushw $196
	jmp isr_common
isr197:
	pushw $0
	pushw $197
	jmp isr_common
isr198:
	pushw $0
	pushw $198
	jmp isr_common
isr199:
	pushw $0
	pushw $199
	jmp isr_common
isr200:
	pushw $0
	pushw $200
	jmp isr_common
isr201:
	pushw $0
	pushw $201
	jmp isr_common
isr202:
	pushw $0
	pushw $202
	jmp isr_common
isr203:
	pushw $0
	pushw $203
	jmp isr_common
isr204:
	pushw $0
	pushw $204
	jmp isr_common
isr205:
	pushw $0
	pushw $205
	jmp isr_common
isr206:
	pushw $0
	pushw $206
	jmp isr_common
isr207:
	pushw $0
	pushw $207
	jmp isr_common
isr208:
	pushw $0
	pushw $208
	jmp isr_common
isr209:
	pushw $0
	pushw $209
	jmp isr_common
isr210:
	pushw $0
	pushw $210
	jmp isr_common
isr211:
	pushw $0
	pushw $211
	jmp isr_common
isr212:
	pushw $0
	pushw $212
	jmp isr_common
isr213:
	pushw $0
	pushw $213
	jmp isr_common
isr214:
	pushw $0
	pushw $214
	jmp isr_common
isr215:
	pushw $0
	pushw $215
	jmp isr_common
isr216:
	pushw $0
	pushw $216
	jmp isr_common
isr217:
	pushw $0
	pushw $217
	jmp isr_common
isr218:
	pushw $0
	pushw $218
	jmp isr_common
isr219:
	pushw $0
	pushw $219
	jmp isr_common
isr220:
	pushw $0
	pushw $220
	jmp isr_common
isr221:
	pushw $0
	pushw $221
	jmp isr_common
isr222:
	pushw $0
	pushw $222
	jmp isr_common
isr223:
	pushw $0
	pushw $223
	jmp isr_common
isr224:
	pushw $0
	pushw $224
	jmp isr_common
isr225:
	pushw $0
	pushw $225
	jmp isr_common
isr226:
	pushw $0
	pushw $226
	jmp isr_common
isr227:
	pushw $0
	pushw $227
	jmp isr_common
isr228:
	pushw $0
	pushw $228
	jmp isr_common
isr229:
	pushw $0
	pushw $229
	jmp isr_common
isr230:
	pushw $0
	pushw $230
	jmp isr_common
isr231:
	pushw $0
	pushw $231
	jmp isr_common
isr232:
	pushw $0
	pushw $232
	jmp isr_common
isr233:
	pushw $0
	pushw $233
	jmp isr_common
isr234:
	pushw $0
	pushw $234
	jmp isr_common
isr235:
	pushw $0
	pushw $235
	jmp isr_common
isr236:
	pushw $0
	pushw $236
	jmp isr_common
isr237:
	pushw $0
	pushw $237
	jmp isr_common
isr238:
	pushw $0
	pushw $238
	jmp isr_common
isr239:
	pushw $0
	pushw $239
	jmp isr_common
isr240:
	pushw $0
	pushw $240
	jmp isr_common
isr241:
	pushw $0
	pushw $241
	jmp isr_common
isr242:
	pushw $0
	pushw $242
	jmp isr_common
isr243:
	pushw $0
	pushw $243
	jmp isr_common
isr244:
	pushw $0
	pushw $244
	jmp isr_common
isr245:
	pushw $0
	pushw $245
	jmp isr_common
isr246:
	pushw $0
	pushw $246
	jmp isr_common
isr247:
	pushw $0
	pushw $247
	jmp isr_common
isr248:
	pushw $0
	pushw $248
	jmp isr_common
isr249:
	pushw $0
	pushw $249
	jmp isr_common
isr250:
	pushw $0
	pushw $250
	jmp isr_common
isr251:
	pushw $0
	pushw $251
	jmp isr_common
isr252:
	pushw $0
	pushw $252
	jmp isr_common
isr253:
	pushw $0
	pushw $253
	jmp isr_common
isr254:
	pushw $0
	pushw $254
	jmp isr_common
isr255:
	pushw $0
	pushw $255
	jmp isr_common

isr_common:
	pusha
	pushw %ds
	pushw %es
	pushw %fs
	pushw %gs
	pushl %esp
	cld
	call isr_handler
	popl %eax
	popw %gs
	popw %fs
	popw %es
	popw %ds
	addl %esp, 8
	iret
.data
.global isrs
isrs:
	.long isr0
	.long isr1
	.long isr2
	.long isr3
	.long isr4
	.long isr5
	.long isr6
	.long isr7
	.long isr8
	.long isr9
	.long isr10
	.long isr11
	.long isr12
	.long isr13
	.long isr14
	.long isr15
	.long isr16
	.long isr17
	.long isr18
	.long isr19
	.long isr20
	.long isr21
	.long isr22
	.long isr23
	.long isr24
	.long isr25
	.long isr26
	.long isr27
	.long isr28
	.long isr29
	.long isr30
	.long isr31
	.long isr32
	.long isr33
	.long isr34
	.long isr35
	.long isr36
	.long isr37
	.long isr38
	.long isr39
	.long isr40
	.long isr41
	.long isr42
	.long isr43
	.long isr44
	.long isr45
	.long isr46
	.long isr47
	.long isr48
	.long isr49
	.long isr50
	.long isr51
	.long isr52
	.long isr53
	.long isr54
	.long isr55
	.long isr56
	.long isr57
	.long isr58
	.long isr59
	.long isr60
	.long isr61
	.long isr62
	.long isr63
	.long isr64
	.long isr65
	.long isr66
	.long isr67
	.long isr68
	.long isr69
	.long isr70
	.long isr71
	.long isr72
	.long isr73
	.long isr74
	.long isr75
	.long isr76
	.long isr77
	.long isr78
	.long isr79
	.long isr80
	.long isr81
	.long isr82
	.long isr83
	.long isr84
	.long isr85
	.long isr86
	.long isr87
	.long isr88
	.long isr89
	.long isr90
	.long isr91
	.long isr92
	.long isr93
	.long isr94
	.long isr95
	.long isr96
	.long isr97
	.long isr98
	.long isr99
	.long isr100
	.long isr101
	.long isr102
	.long isr103
	.long isr104
	.long isr105
	.long isr106
	.long isr107
	.long isr108
	.long isr109
	.long isr110
	.long isr111
	.long isr112
	.long isr113
	.long isr114
	.long isr115
	.long isr116
	.long isr117
	.long isr118
	.long isr119
	.long isr120
	.long isr121
	.long isr122
	.long isr123
	.long isr124
	.long isr125
	.long isr126
	.long isr127
	.long isr128
	.long isr129
	.long isr130
	.long isr131
	.long isr132
	.long isr133
	.long isr134
	.long isr135
	.long isr136
	.long isr137
	.long isr138
	.long isr139
	.long isr140
	.long isr141
	.long isr142
	.long isr143
	.long isr144
	.long isr145
	.long isr146
	.long isr147
	.long isr148
	.long isr149
	.long isr150
	.long isr151
	.long isr152
	.long isr153
	.long isr154
	.long isr155
	.long isr156
	.long isr157
	.long isr158
	.long isr159
	.long isr160
	.long isr161
	.long isr162
	.long isr163
	.long isr164
	.long isr165
	.long isr166
	.long isr167
	.long isr168
	.long isr169
	.long isr170
	.long isr171
	.long isr172
	.long isr173
	.long isr174
	.long isr175
	.long isr176
	.long isr177
	.long isr178
	.long isr179
	.long isr180
	.long isr181
	.long isr182
	.long isr183
	.long isr184
	.long isr185
	.long isr186
	.long isr187
	.long isr188
	.long isr189
	.long isr190
	.long isr191
	.long isr192
	.long isr193
	.long isr194
	.long isr195
	.long isr196
	.long isr197
	.long isr198
	.long isr199
	.long isr200
	.long isr201
	.long isr202
	.long isr203
	.long isr204
	.long isr205
	.long isr206
	.long isr207
	.long isr208
	.long isr209
	.long isr210
	.long isr211
	.long isr212
	.long isr213
	.long isr214
	.long isr215
	.long isr216
	.long isr217
	.long isr218
	.long isr219
	.long isr220
	.long isr221
	.long isr222
	.long isr223
	.long isr224
	.long isr225
	.long isr226
	.long isr227
	.long isr228
	.long isr229
	.long isr230
	.long isr231
	.long isr232
	.long isr233
	.long isr234
	.long isr235
	.long isr236
	.long isr237
	.long isr238
	.long isr239
	.long isr240
	.long isr241
	.long isr242
	.long isr243
	.long isr244
	.long isr245
	.long isr246
	.long isr247
	.long isr248
	.long isr249
	.long isr250
	.long isr251
	.long isr252
	.long isr253
	.long isr254
	.long isr255
